version: "3"
services:
  postgres:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: docker.io/library/adminer:latest
    ports:
      - "9000:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: